[package]
name = "only-sdk-examples"
version = "1.0.0"
authors = ["Egal"]
edition = "2024"
rust-version = "1.89.0"
license = "Apache-2.0"
publish = false
repository = "https://github.com/milon-labs/"
homepage = "https://milon.com"


[dependencies]
milon_idl_core = { package = "milon_idl_core", path = "../milon-sdk-rs/idl-core", features = ["json"] }
milon_idl_macro = { package = "milon_idl_macro", path = "../milon-sdk-rs/idl-macro" }
milon_local_wallet = { package = "milon_local_wallet", path = "../milon-sdk-rs/local-wallet" }
milon_provider = { package = "milon_provider", path = "../milon-sdk-rs/provider" }
milon_primitives = { package = "milon_primitives", path = "../milon-sdk-rs/primitives" }
milon_rpc_client = { package = "milon_rpc_client", path = "../milon-sdk-rs/rpc-client" }
milon_transport = { package = "milon_transport", path = "../milon-sdk-rs/transport", features = ["grpc"] }
milon-client = { package = "milon-client", path = "../milon-sdk-rs/milon-client", features = ["grpc"] }

milon_wallet = { package = "milon_wallet", path = "../../Milon/crates/wallet" }
milon_crypto = { package = "milon_crypto", path = "../../Milon/crates/crypto" }

infra-core = { path = "../../app-infra/infra-core" }
infra-tracing = { path = "../../app-infra/infra-tracing", features = ["test-utils"] }

anyhow = "1"
tracing = "0.1"
env_logger = "0.11"
tokio = { version = "1.49", features = ["full"] }
inventory = "0.3"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
postcard = { version = "1.1", features = ["use-std"] }
bytes = "1.11"
blst = "0.3"
hex = "0.4"
url = "2"
