infra_core::define_app_error_codes! {
    ExmErr("EXM") {
        ClaimFaucetWithCooldownRemaining = (1001, "claim_faucet_with_cooldown_remaining"),
        TokenMintErr = (1002, "Token mint error"),
        BalanceOfErr = (1003, "Query balance of error"),
        MetadataErr = (1004, "Query token metadata error"),
        CreateTokenErr = (1005, "Create token error"),
        BurnErr = (1006, "Burn token error"),
        TransferErr = (1007, "Transfer token error"),
        FreezeErr = (1008, "Freeze token error"),
        UnfreezeErr = (1009, "Unfreeze token error"),
        ApprovalOfErr = (1010, "Query token approval error"),
        ApproveErr = (1011, "Approve token error"),
        RevokeErr = (1012, "Revoke token approval error"),
        TransferFromErr = (1013, "Transfer token from error"),
        Multicall2Err = (1014, "Multicall error"),
        SendTransactionErr = (1015, "Send transaction error"),
        AccountErr = (1016, "Query account error"),
        CreateAccountErr = (1017, "Create account error"),
        CreateMultisigErr = (1018, "Create multisig account error"),
        ListSignersErr = (1019, "List account signers error"),
        AddSignerErr = (1020, "Add account signer error"),
        AddSignersErr = (1021, "Add account signers error"),
        SetThresholdErr = (1022, "Set account threshold error"),
        RemoveSignerErr = (1023, "Remove account signer error"),
        SetSignerWeightErr = (1024, "Set signer weight error"),
        VoteInitErr = (1025, "Initialize vote error"),
        GetVoteErr = (1026, "Query vote error"),
        VoteErr = (1027, "Vote error"),
        SendVotedTransactionErr = (1028, "Send voted transaction error"),
        ListActiveVotesErr = (1029, "List active votes error"),
        ClaimFaucetErr = (1030, "Claim faucet error"),
        // TokenBurnErr = (1031, "Token burn error"),
        // TokenTransfertErr = (1032, "Token transfer error"),
        // TokenFreezeErr = (1033, "Token freeze error"),
        // TokenUnfreezeErr = (1034, "Token unfreeze error"),
        // TokenApproveErr = (1035, "Token approve error"),
        // TokenRevokeErr = (1036, "Token revoke error"),
        // TokenTransfertFromErr = (1037, "Token transfer from error"),
    }
}
